Block
Block是C、C++、OC中的词法闭包，可接受参数，也可返回值，可以分配在栈或堆上，也可以是全局的
Block的语法结构:return_type (^block_name) (parameters)
在声明Block的范围里，所有变量都可以为其所捕获
默认情况下，为Block所捕获的变量，不可以在Block中修改
声明变量时，添加__block修饰符后，可以在Block内修改
如果Block所捕获的变量是对象类型，就会自动保留它
如果将Block定义在OC类的实例方法中，Block可以访问类的所有实例变量及self变量，而且Block总能修改实例变量，无需添加__block
如果通过读取或者写入操作捕获了实例变量，那么也会自动把self变量一并捕获了，因为实例变量是与self所指的实例关联的
Block中直接访问实例变量和通过self来访问是等效的
Block在捕获self时也会将其保留，如果self所指代的对象同时也保留了Blcok，就会导致保留环
Block会把所捕获的所有变量都拷贝一份，拷贝的不是对象本身，而是指向这些对象的指针变量
Global Block使用的整个内存区域，在编译期就已经完全确定了
